---
version: "2"
services:
  nextcloud:
    image: linuxserver/nextcloud
    container_name: nextcloud
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${UNIQUE_NAME}_config:/config
    restart: unless-stopped
    depends_on:
      - nextcloud_db
    networks:
    - public
    labels:
    - traefik.http.routers.${UNIQUE_NAME}.rule=Host(`${URL}`)
    - traefik.http.routers.${UNIQUE_NAME}.tls=true
    - traefik.http.routers.${UNIQUE_NAME}.tls.certresolver=leresolver
    - traefik.port=80
  nextcloud_db:
    image: linuxserver/mariadb
    container_name: nextcloud_db
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${Timezone}
      - MYSQL_DATABASE=nextcloud_db
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - ${UNIQUE_NAME}_db:/config
    restart: unless-stopped
volumes:
  ${UNIQUE_NAME}_config:
  ${UNIQUE_NAME}_db:
networks:
  public:
    external: true
